apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::315301634286:role/kubectl-ec2-role
      username: kubectl-ec2
      groups:
        - system:masters
    - rolearn: arn:aws:iam::315301634286:role/my-eks-cluster-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
